/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LCD.h>
#include <Hall_To_PSOC.h>
#include <Hall_To_PSOC_aliases.h>
#include <PWM.h>
#include <Hall_Counter.h>
#include <ISR_Hall.h>
#include <ISR_Overflow.h>
#include <Input_LED.h>
#include <Input_LED_aliases.h>
#include <Clock_Hall.h>
#include <ISR_100_Lines.h>
#include <Vertical_Sync_Frame.h>
#include <Vertical_Sync_Frame_aliases.h>
#include <Lines_Per_Frame_Counter.h>
#include <Line_Timer.h>
#include <Steering_Output.h>
#include <Steering_Output_aliases.h>
#include <Horizontal_Sync_Line.h>
#include <Horizontal_Sync_Line_aliases.h>
#include <Composite_Video.h>
#include <Composite_Video_aliases.h>
#include <Camera_Comp.h>
#include <Clock_Steering.h>
#include <ISR_50_Lines.h>
#include <Camera_Threshold.h>
#include <PWM_Steering.h>
#include <elevator_test.h>
#include <elevator_test_aliases.h>
#include <Pin_1.h>
#include <Pin_1_aliases.h>
#include <elevator_input_2.h>
#include <elevator_input_2_aliases.h>
#include <drive_output_2.h>
#include <drive_output_2_aliases.h>
#include <drive_output_1.h>
#include <drive_output_1_aliases.h>
#include <elevator_input.h>
#include <elevator_input_aliases.h>
#include <Elevator_Comparator.h>
#include <Elevator_Threshold.h>
#include <ISR_Elevator.h>
#include <Drive_Control_Reg.h>
#include <Pin_2.h>
#include <Pin_2_aliases.h>
#include <Elevator_Comparator_1.h>
#include <Pin_3.h>
#include <Pin_3_aliases.h>
#include <ISR_Elevator_2.h>
#include <Wait_Counter.h>
#include <Wait_Clock.h>
#include <ISR_Wait.h>
#include <Pin_4.h>
#include <Pin_4_aliases.h>
#include <ADC_DelSig.h>
#include <LCD_LCDPort.h>
#include <LCD_LCDPort_aliases.h>
#include <ADC_DelSig_theACLK.h>
#include <ADC_DelSig_Ext_CP_Clk.h>
#include <ADC_DelSig_AMux.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
